"""
Knowledge Base Loader — helps agents access PTS documents.
Auto-generated by extract_pdf_kb.py, extended by ArchitectAI.

Improvements over v1:
- reset_loader() for clean test isolation
- search_sections() lightweight keyword-based section finder (RAG placeholder)
- Higher default context limits (Gemini Flash supports ~1M token ctx)
- Stores per-agent KB strings for reuse across calls
"""

import re
import json
from pathlib import Path
from typing import Optional, Dict, List, Any

from loguru import logger
from src.memory.vector_store import get_vector_store


class KnowledgeBaseLoader:
    # Default chars to include per document in prompt context.
    # Gemini Flash has a 1M-token context; we can be generous.
    # typrum.txt is 339k chars — we sample more now (was 5000).
    DEFAULT_CHAR_LIMITS: Dict[str, int] = {
        "typrum":         30_000,   # Room type specs — large, need breadth
        "funktionskrav":  10_000,   # Functional requirements
        "tekniska_krav":  10_000,   # Technical requirements
        "brand":           6_000,   # Fire safety
        "miljokrav":       5_000,   # Environmental
        "ytskikt":         4_000,   # Surface materials (smallest doc)
    }
    DEFAULT_CHAR_LIMIT = 8_000  # Fallback for unknown categories

    def __init__(self, kb_dir: Path = None):
        if kb_dir is None:
            # Find KB relative to this file or from project root
            candidate1 = Path(__file__).parent.parent.parent / "compliance_kb" / "SE" / "healthcare"
            candidate2 = Path("compliance_kb") / "SE" / "healthcare"
            if candidate1.exists():
                kb_dir = candidate1
            elif candidate2.exists():
                kb_dir = candidate2
            else:
                kb_dir = candidate1  # Use first, even if it doesn't exist yet
        self.kb_dir = Path(kb_dir)
        self.index = self._load_index()
        # Cache full document texts so we can search them without re-reading disk
        self._doc_cache: Dict[str, str] = {}
        
        # Initialize vector store
        try:
            self.vector_store = get_vector_store()
        except Exception as e:
            logger.warning(f"[KB-Loader] Failed to init vector store: {e}. Semantic search disabled.")
            self.vector_store = None

    def _load_index(self) -> dict:
        """Load the KB index."""
        index_file = self.kb_dir / "index.json"
        if index_file.exists():
            return json.loads(index_file.read_text(encoding="utf-8"))
        return {}

    def get_document(self, category: str) -> Optional[str]:
        """Load a single document by category (full text, cached)."""
        if category in self._doc_cache:
            return self._doc_cache[category]
        doc_meta = self.index.get("documents", {}).get(category)
        if not doc_meta:
            return None
        text_file = self.kb_dir / doc_meta["text_file"]
        if text_file.exists():
            text = text_file.read_text(encoding="utf-8")
            self._doc_cache[category] = text
            return text
        return None

    def get_documents_for_agent(self, agent_id: str) -> Dict[str, str]:
        """Load all documents relevant to a specific agent (full text)."""
        result = {}
        for category, doc_meta in self.index.get("documents", {}).items():
            if agent_id in doc_meta.get("agents", []):
                content = self.get_document(category)
                if content:
                    result[category] = content
        return result

    def get_prompt_context(self, agent_id: str, char_limits: Dict[str, int] = None) -> str:
        """
        Get formatted KB context string for system prompt injection.

        Uses per-category char limits (much larger than v1).
        Pass char_limits={} to use defaults, or override per category.
        """
        docs = self.get_documents_for_agent(agent_id)
        if not docs:
            return ""

        limits = {**self.DEFAULT_CHAR_LIMITS, **(char_limits or {})}

        lines = ["\n### REGULATORY KNOWLEDGE BASE (PTS Documents)\n"]
        for category, content in docs.items():
            limit = limits.get(category, self.DEFAULT_CHAR_LIMIT)
            lines.append(f"\n#### {category.upper()}\n")
            lines.append(content[:limit])
            if len(content) > limit:
                pct = int(limit / len(content) * 100)
                lines.append(
                    f"\n[... document continues — showing first {limit:,} of "
                    f"{len(content):,} chars ({pct}%). Use search_sections() for targeted lookup. ...]\n"
                )

        return "\n".join(lines)

    def search_sections(
        self,
        category: str,
        keywords: List[str],
        context_chars: int = 600,
        max_hits: int = 5,
    ) -> str:
        """
        Lightweight keyword-based section finder — a RAG placeholder until
        ChromaDB vector search is integrated.

        Searches the full document for lines containing any of the keywords
        and returns surrounding context for each hit, deduplicated.

        Args:
            category:      KB category e.g. "typrum"
            keywords:      List of search terms (case-insensitive)
            context_chars: Characters of context to include around each hit
            max_hits:      Maximum number of distinct hits to return

        Returns:
            Formatted string of matching excerpts, empty if nothing found.
        """
        text = self.get_document(category)
        if not text:
            return ""

        pattern = re.compile(
            "|".join(re.escape(kw) for kw in keywords),
            re.IGNORECASE,
        )

        excerpts: List[str] = []
        seen_positions: set = set()

        for match in pattern.finditer(text):
            if len(excerpts) >= max_hits:
                break
            start = max(0, match.start() - context_chars // 2)
            end   = min(len(text), match.end() + context_chars // 2)

            # Deduplicate overlapping windows
            window_key = start // (context_chars // 2)
            if window_key in seen_positions:
                continue
            seen_positions.add(window_key)

            excerpt = text[start:end].strip()
            excerpts.append(f"[{category.upper()} — near '{match.group()}']\n{excerpt}")

        if not excerpts:
            return ""

        return "\n\n---\n\n".join(excerpts)

    def get_semantic_context(
        self,
        query: str,
        agent_id: str,
        n_results: int = 5,
        category: str = None
    ) -> str:
        """
        Retrieves relevant text chunks from the vector store using RAG.
        
        Args:
            query: The semantic search query (e.g. "brandskyddskrav fÃ¶r vÃ¥rdcentral")
            agent_id: The search context agent
            n_results: Number of chunks to return
            category: Optional filter by KB category (e.g. "typrum")
            
        Returns:
            Formatted context string for LLM injection.
        """
        if not self.vector_store or self.vector_store.get_count() == 0:
            # Fallback to prefix-based context if RAG index not ready
            logger.warning(f"[KB-Loader] Vector store empty or disabled, falling back to prefix.")
            return self.get_prompt_context(agent_id)
        
        where = {"category": category} if category else None
        
        # If no category, we can search all documents the agent is interested in
        # Note: ChromaDB 'where' with '$in' is supported if we wanted to filter by multiple
        
        logger.info(f"[KB-Loader] Querying vector store for '{query}' (agent={agent_id})...")
        hits = self.vector_store.query(query, n_results=n_results, where=where)
        
        if not hits:
            return ""
            
        lines = [f"\n### REGULATORY KNOWLEDGE (Semantic Retrieval for: '{query}')\n"]
        for i, hit in enumerate(hits, 1):
            meta = hit["metadata"]
            source = meta.get("title", meta.get("source", "Unknown"))
            page = meta.get("page", "N/A")
            lines.append(f"#### Match {i} — {source} [Page {page}]\n")
            lines.append(hit["document"].strip() + "\n")
            
        return "\n".join(lines)

    def get_targeted_context(
        self,
        agent_id: str,
        keywords: List[str],
        base_chars: int = 3000,
        search_chars: int = 600,
    ) -> str:
        """
        Combines a base prefix of each document with keyword-targeted excerpts.
        More relevant than pure prefix, less overhead than full RAG.

        Use this in system prompts for agents that have specific domain focus.
        """
        docs = self.get_documents_for_agent(agent_id)
        if not docs:
            return ""

        parts = ["\n### REGULATORY KNOWLEDGE BASE (PTS Documents — targeted)\n"]
        for category, content in docs.items():
            limit = min(base_chars, self.DEFAULT_CHAR_LIMITS.get(category, base_chars))
            header = f"\n#### {category.upper()}\n"
            base_excerpt = content[:limit]

            # Search for keywords in the full doc
            targeted = self.search_sections(category, keywords, context_chars=search_chars, max_hits=3)
            if targeted:
                parts.append(header + base_excerpt + "\n\n[Targeted excerpts:]\n" + targeted)
            else:
                parts.append(header + base_excerpt)

        return "\n".join(parts)


# ---------------------------------------------------------------------------
# Module-level singleton — one loader shared across the process
# ---------------------------------------------------------------------------
_loader: Optional[KnowledgeBaseLoader] = None


def get_loader(kb_dir: Path = None) -> KnowledgeBaseLoader:
    """Return the shared KnowledgeBaseLoader singleton, creating it if needed."""
    global _loader
    if _loader is None:
        _loader = KnowledgeBaseLoader(kb_dir)
    return _loader


def reset_loader() -> None:
    """
    Reset the singleton so the next call to get_loader() creates a fresh instance.
    Use this in test setUp/tearDown or pytest fixtures to ensure test isolation.

    Example (pytest conftest.py):
        import pytest
        from src.memory.kb_loader import reset_loader

        @pytest.fixture(autouse=True)
        def isolate_kb():
            reset_loader()
            yield
            reset_loader()
    """
    global _loader
    _loader = None
