"""
Knowledge Base Loader — helps agents access PTS documents.
Auto-generated by extract_pdf_kb.py
"""

import json
from pathlib import Path
from typing import Optional, Dict

class KnowledgeBaseLoader:
    def __init__(self, kb_dir: Path = None):
        if kb_dir is None:
            # Find KB in compliance_kb/SE/healthcare/ from project root
            # Try multiple paths: relative to this file, or from project root
            candidate1 = Path(__file__).parent.parent.parent / "compliance_kb" / "SE" / "healthcare"
            candidate2 = Path("compliance_kb") / "SE" / "healthcare"
            if candidate1.exists():
                kb_dir = candidate1
            elif candidate2.exists():
                kb_dir = candidate2
            else:
                kb_dir = candidate1  # Use first, even if doesn't exist yet
        self.kb_dir = Path(kb_dir)
        self.index = self._load_index()
    
    def _load_index(self) -> dict:
        """Load the KB index."""
        index_file = self.kb_dir / "index.json"
        if index_file.exists():
            return json.loads(index_file.read_text(encoding="utf-8"))
        return {}
    
    def get_document(self, category: str) -> Optional[str]:
        """Load a single document by category."""
        doc_meta = self.index.get("documents", {}).get(category)
        if not doc_meta:
            return None
        text_file = self.kb_dir / doc_meta["text_file"]
        if text_file.exists():
            return text_file.read_text(encoding="utf-8")
        return None
    
    def get_documents_for_agent(self, agent_id: str) -> Dict[str, str]:
        """Load all documents relevant to a specific agent."""
        result = {}
        for category, doc_meta in self.index.get("documents", {}).items():
            if agent_id in doc_meta.get("agents", []):
                content = self.get_document(category)
                if content:
                    result[category] = content
        return result
    
    def get_prompt_context(self, agent_id: str) -> str:
        """Get formatted KB context for system prompt."""
        docs = self.get_documents_for_agent(agent_id)
        if not docs:
            return ""
        
        lines = ["\n### REGULATORY KNOWLEDGE BASE (PTS Documents)\n"]
        for category, content in docs.items():
            lines.append(f"\n#### {category.upper()}\n")
            lines.append(content[:2000])  # Truncate to first 2000 chars per doc
            if len(content) > 2000:
                lines.append("\n[... document truncated for context length ...]\n")
        
        return "\n".join(lines)

# Singleton instance
_loader = None

def get_loader(kb_dir: Path = None) -> KnowledgeBaseLoader:
    global _loader
    if _loader is None:
        _loader = KnowledgeBaseLoader(kb_dir)
    return _loader
